name: Summary Extension
run-name: Summary Extension
on:
  pull_request:
    branches:
      - main
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npx nx export extension-frontend
      - name: Store exported frontend
        uses: actions/upload-artifact@v3
        with:
          name: extension-frontend-source.zip
          path: ./pkg/bin/summary-extension/dist
  binary:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - uses: actions/checkout@v3
      - name: Get exported frontend for extension
        uses: actions/download-artifact@v3
        with:
          name: extension-frontend-source.zip
          path: ./pkg/bin/summary-extension/dist
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o clipcap-summary pkg/bin/summary-extension/main.go
      - name: Unveil Summary Extension Binary
        uses: actions/upload-artifact@v3
        with:
          name: clipcap-summary-linux-amd64
          path: ./clipcap-summary
